/**
 * مكتبة الأوامر — رِفد
 * 50+ قالب نصي وبصري للمتاجر السعودية مع تحديثات شهرية مستمرة
 */

export type PromptType = "text" | "image";
export type PromptCategory =
  | "launch"
  | "offer"
  | "season"
  | "product"
  | "social"
  | "trust"
  | "video";

export type Prompt = {
  id: string;
  title: string;
  description: string;
  type: PromptType;
  category: PromptCategory;
  badge?: "جديد" | "شائع" | "موصى";
  freeTier: boolean;
  estimatedTime: string;
  variables: string[];
  sample?: string;
};

export const CATEGORIES: { id: PromptCategory; label: string; emoji: string }[] = [
  { id: "launch", label: "إطلاق", emoji: "🚀" },
  { id: "offer", label: "عرض", emoji: "🏷️" },
  { id: "season", label: "موسم", emoji: "🌙" },
  { id: "product", label: "وصف منتج", emoji: "🛍️" },
  { id: "social", label: "محتوى اجتماعي", emoji: "📱" },
  { id: "trust", label: "ثقة", emoji: "🤝" },
  { id: "video", label: "فيديو", emoji: "🎬" },
];

export const PROMPTS: Prompt[] = [
  // —— نص: سوشيال (6) ——
  {
    id: "ig-post-launch",
    title: "منشور إنستقرام لإطلاق منتج",
    description: "منشور جذاب بالعامية السعودية لإطلاق منتج جديد مع هاشتاقات",
    type: "text",
    category: "launch",
    badge: "شائع",
    freeTier: true,
    estimatedTime: "10 ثواني",
    variables: ["اسم المنتج", "السعر", "الميزة الرئيسية"],
    sample: "🔥 وصل أخيراً! [اسم المنتج] بسعر يفرّح القلب — جربوه واحكموا بأنفسكم.",
  },
  {
    id: "tiktok-hook",
    title: "هوك تيك توك (3 ثواني)",
    description: "جملة افتتاحية تشدّ المشاهد من أول ثانية",
    type: "text",
    category: "social",
    badge: "جديد",
    freeTier: true,
    estimatedTime: "5 ثواني",
    variables: ["نوع المنتج", "الجمهور"],
  },
  {
    id: "snap-story",
    title: "نص قصة سناب",
    description: "نص قصير وجذاب لقصة سناب شات",
    type: "text",
    category: "social",
    freeTier: true,
    estimatedTime: "5 ثواني",
    variables: ["الموضوع"],
  },
  {
    id: "x-thread",
    title: "ثريد X (تويتر) — 5 تغريدات",
    description: "ثريد متسلسل يحكي قصة منتجك أو متجرك",
    type: "text",
    category: "social",
    freeTier: false,
    estimatedTime: "15 ثانية",
    variables: ["الموضوع", "النبرة"],
  },
  {
    id: "linkedin-post",
    title: "منشور لينكدإن احترافي",
    description: "منشور بنبرة احترافية للوصول لرواد الأعمال",
    type: "text",
    category: "social",
    freeTier: false,
    estimatedTime: "15 ثانية",
    variables: ["الموضوع", "الصناعة"],
  },
  {
    id: "ig-caption-product",
    title: "كابشن إنستقرام لصورة منتج",
    description: "كابشن قصير + emoji + CTA + هاشتاقات",
    type: "text",
    category: "social",
    badge: "موصى",
    freeTier: true,
    estimatedTime: "8 ثواني",
    variables: ["اسم المنتج", "الميزة"],
  },

  // —— نص: منتجات (5) ——
  {
    id: "product-desc-short",
    title: "وصف منتج قصير (سلة/زد)",
    description: "وصف 50 كلمة يبيع — جاهز للنسخ في متجرك",
    type: "text",
    category: "product",
    badge: "شائع",
    freeTier: true,
    estimatedTime: "10 ثواني",
    variables: ["اسم المنتج", "الفئة", "الميزات"],
  },
  {
    id: "product-desc-long",
    title: "وصف منتج تفصيلي + مواصفات",
    description: "وصف كامل + bullets + ضمانات + شحن",
    type: "text",
    category: "product",
    freeTier: false,
    estimatedTime: "20 ثانية",
    variables: ["اسم المنتج", "الفئة", "السعر"],
  },
  {
    id: "product-bullets",
    title: "نقاط مميزات المنتج",
    description: "5 نقاط احترافية تبرز فوائد منتجك",
    type: "text",
    category: "product",
    freeTier: true,
    estimatedTime: "8 ثواني",
    variables: ["اسم المنتج"],
  },
  {
    id: "product-faq",
    title: "أسئلة شائعة لصفحة منتج",
    description: "10 أسئلة وأجوبة جاهزة لزيادة الثقة",
    type: "text",
    category: "product",
    freeTier: false,
    estimatedTime: "20 ثانية",
    variables: ["اسم المنتج"],
  },
  {
    id: "product-bundle",
    title: "وصف عرض حزمة (Bundle)",
    description: "نص يشرح قيمة العرض ويحفّز الشراء",
    type: "text",
    category: "product",
    freeTier: false,
    estimatedTime: "12 ثانية",
    variables: ["المنتجات", "الخصم"],
  },

  // —— نص: إعلانات (4) ——
  {
    id: "meta-ad-copy",
    title: "نص إعلان ميتا (فيسبوك/إنستقرام)",
    description: "Headline + Primary Text + Description جاهزين",
    type: "text",
    category: "offer",
    badge: "شائع",
    freeTier: true,
    estimatedTime: "12 ثانية",
    variables: ["المنتج", "الجمهور", "الهدف"],
  },
  {
    id: "snap-ad-copy",
    title: "نص إعلان سناب",
    description: "نص قصير وقوي مناسب لإعلانات سناب",
    type: "text",
    category: "offer",
    freeTier: false,
    estimatedTime: "10 ثواني",
    variables: ["المنتج", "العرض"],
  },
  {
    id: "google-ad-copy",
    title: "إعلان قوقل (نص + امتدادات)",
    description: "Headlines + Descriptions حسب أفضل ممارسات قوقل",
    type: "text",
    category: "offer",
    freeTier: false,
    estimatedTime: "15 ثانية",
    variables: ["المنتج", "الكلمات المفتاحية"],
  },
  {
    id: "tiktok-ad-script",
    title: "سكربت إعلان تيك توك (15 ثانية)",
    description: "سكربت قصير بثلاث مشاهد + voiceover",
    type: "text",
    category: "video",
    badge: "جديد",
    freeTier: false,
    estimatedTime: "20 ثانية",
    variables: ["المنتج", "الجمهور"],
  },

  // —— نص: بريد (3) ——
  {
    id: "email-welcome",
    title: "إيميل ترحيب بعميل جديد",
    description: "إيميل دافئ بالعامية السعودية لأول طلب",
    type: "text",
    category: "trust",
    freeTier: true,
    estimatedTime: "12 ثانية",
    variables: ["اسم المتجر"],
  },
  {
    id: "email-cart-abandon",
    title: "إيميل سلة متروكة",
    description: "إيميل ذكي يرجّع العميل لإكمال الشراء",
    type: "text",
    category: "trust",
    badge: "موصى",
    freeTier: false,
    estimatedTime: "15 ثانية",
    variables: ["اسم المتجر", "المنتج"],
  },
  {
    id: "email-promo",
    title: "إيميل عرض ترويجي",
    description: "إيميل يحوّل العروض لمبيعات",
    type: "text",
    category: "offer",
    freeTier: false,
    estimatedTime: "12 ثانية",
    variables: ["العرض", "الفترة"],
  },

  // —— نص: SEO (3) ——
  {
    id: "seo-meta",
    title: "Meta title + description",
    description: "عنوان ووصف SEO محسّن للسوق السعودي",
    type: "text",
    category: "trust",
    freeTier: true,
    estimatedTime: "8 ثواني",
    variables: ["الموضوع", "الكلمات المفتاحية"],
  },
  {
    id: "seo-blog",
    title: "مقال مدوّنة (1000 كلمة)",
    description: "مقال SEO كامل بهيكل H1-H3",
    type: "text",
    category: "trust",
    freeTier: false,
    estimatedTime: "45 ثانية",
    variables: ["الموضوع", "الكلمات المفتاحية"],
  },
  {
    id: "seo-keywords",
    title: "اقتراح كلمات مفتاحية سعودية",
    description: "20 كلمة مفتاحية بالعربي مع نية البحث",
    type: "text",
    category: "trust",
    freeTier: false,
    estimatedTime: "10 ثواني",
    variables: ["المنتج/الخدمة"],
  },

  // —— نص: دعم (2) ——
  {
    id: "whatsapp-reply",
    title: "رد واتساب احترافي",
    description: "رد سريع ومهذب على استفسار عميل",
    type: "text",
    category: "trust",
    freeTier: true,
    estimatedTime: "5 ثواني",
    variables: ["نوع الاستفسار"],
  },
  {
    id: "complaint-reply",
    title: "رد على شكوى عميل",
    description: "رد دبلوماسي يحلّ المشكلة ويحفظ العلاقة",
    type: "text",
    category: "trust",
    freeTier: false,
    estimatedTime: "10 ثواني",
    variables: ["الشكوى"],
  },

  // —— نص: مناسبات (3) ——
  {
    id: "ramadan-post",
    title: "منشور رمضاني ترويجي",
    description: "منشور بروح رمضانية + عرض",
    type: "text",
    category: "season",
    badge: "شائع",
    freeTier: true,
    estimatedTime: "10 ثواني",
    variables: ["العرض"],
  },
  {
    id: "national-day",
    title: "محتوى اليوم الوطني السعودي",
    description: "محتوى وطني فخور + عرض",
    type: "text",
    category: "season",
    freeTier: true,
    estimatedTime: "10 ثواني",
    variables: ["العرض"],
  },
  {
    id: "white-friday",
    title: "حملة الجمعة البيضاء",
    description: "نصوص حملة كاملة (تشويق + إطلاق + تذكير)",
    type: "text",
    category: "offer",
    badge: "موصى",
    freeTier: false,
    estimatedTime: "20 ثانية",
    variables: ["الخصومات"],
  },

  // —— نص: متجر (3) ——
  {
    id: "about-us",
    title: "صفحة من نحن",
    description: "نص قصة العلامة التجارية بأسلوب يبيع",
    type: "text",
    category: "trust",
    freeTier: true,
    estimatedTime: "15 ثانية",
    variables: ["اسم المتجر", "القصة"],
  },
  {
    id: "shipping-policy",
    title: "سياسة الشحن والإرجاع",
    description: "نص قانوني واضح ومتوافق مع الأنظمة السعودية",
    type: "text",
    category: "trust",
    freeTier: false,
    estimatedTime: "15 ثانية",
    variables: ["مدة الشحن", "سياسة الإرجاع"],
  },
  {
    id: "store-tagline",
    title: "شعار/تاج لاين للمتجر",
    description: "5 خيارات تاج لاين قصيرة لا تُنسى",
    type: "text",
    category: "launch",
    freeTier: true,
    estimatedTime: "8 ثواني",
    variables: ["اسم المتجر", "النشاط"],
  },

  // ============== الصور (10) ==============
  {
    id: "img-white-friday",
    title: "بوستر عرض الجمعة البيضاء",
    description: "بوستر إعلاني بنص عربي بارز ومناسب لإنستقرام",
    type: "image",
    category: "offer",
    badge: "شائع",
    freeTier: true,
    estimatedTime: "15 ثانية",
    variables: ["نص العرض", "اسم المتجر", "اللون الأساسي"],
  },
  {
    id: "img-product-enhance",
    title: "تحسين صورة منتج (خلفية بيضاء)",
    description: "ارفع صورة منتجك ونحسّنها لخلفية احترافية",
    type: "image",
    category: "product",
    badge: "موصى",
    freeTier: true,
    estimatedTime: "20 ثانية",
    variables: ["صورة المنتج"],
  },
  {
    id: "img-ig-story-launch",
    title: "قصة إنستقرام لإطلاق منتج",
    description: "قصة عمودية 9:16 بنص عربي ضخم + هوية المتجر",
    type: "image",
    category: "launch",
    freeTier: true,
    estimatedTime: "15 ثانية",
    variables: ["اسم المنتج", "تاريخ الإطلاق"],
  },
  {
    id: "img-ramadan-poster",
    title: "بوستر رمضان كريم",
    description: "بوستر بزخارف رمضانية أصيلة + نص عرضك",
    type: "image",
    category: "season",
    freeTier: false,
    estimatedTime: "20 ثانية",
    variables: ["نص العرض", "اسم المتجر"],
  },
  {
    id: "img-store-banner",
    title: "بنر المتجر الإلكتروني (هيدر)",
    description: "بنر هوريزونتال 1920×600 لرأس متجرك",
    type: "image",
    category: "launch",
    freeTier: false,
    estimatedTime: "20 ثانية",
    variables: ["اسم المتجر", "الرسالة"],
  },
  {
    id: "img-carousel-3",
    title: "كاروسيل إنستقرام (3 صور متناسقة)",
    description: "ثلاث صور بهوية موحّدة لمنشور كاروسيل",
    type: "image",
    category: "social",
    badge: "جديد",
    freeTier: false,
    estimatedTime: "30 ثانية",
    variables: ["الموضوع", "اللون"],
  },
  {
    id: "img-meta-ad",
    title: "إعلان ممول لميتا/سناب",
    description: "صورة إعلانية مع نص عربي + CTA — جودة عالية",
    type: "image",
    category: "offer",
    freeTier: false,
    estimatedTime: "30 ثانية",
    variables: ["المنتج", "العرض"],
  },
  {
    id: "img-thank-you",
    title: "بطاقة شكر للعميل",
    description: "بطاقة رقمية ترسلها للعميل بعد الشراء",
    type: "image",
    category: "trust",
    freeTier: true,
    estimatedTime: "12 ثانية",
    variables: ["اسم العميل", "اسم المتجر"],
  },
  {
    id: "img-national-day",
    title: "بوستر اليوم الوطني السعودي",
    description: "تصميم وطني فخور بألوان العلم",
    type: "image",
    category: "season",
    badge: "موصى",
    freeTier: false,
    estimatedTime: "30 ثانية",
    variables: ["نص العرض", "اسم المتجر"],
  },
  {
    id: "img-infographic",
    title: "إنفوجرافيك عربي بسيط",
    description: "إنفوجرافيك بنقاط مرئية بالعربي",
    type: "image",
    category: "trust",
    freeTier: false,
    estimatedTime: "25 ثانية",
    variables: ["الموضوع", "النقاط"],
  },
  {
    id: "img-reel-cover",
    title: "غلاف Reel عربي احترافي",
    description: "غلاف عمودي قوي بعنوان عربي واضح ومهيأ لجذب المشاهد من أول ثانية",
    type: "image",
    category: "video",
    badge: "جديد",
    freeTier: false,
    estimatedTime: "25 ثانية",
    variables: ["عنوان الريل", "اسم المتجر", "لون الهوية"],
  },
];

export const TEXT_PROMPTS = PROMPTS.filter((p) => p.type === "text");
export const IMAGE_PROMPTS = PROMPTS.filter((p) => p.type === "image");
