/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VsChatgptRouteImport } from './routes/vs-chatgpt'
import { Route as VideoProvidersRouteImport } from './routes/video-providers'
import { Route as VideoProviderRouteImport } from './routes/video-provider'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProofCenterRouteImport } from './routes/proof-center'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForPerfumesBeautyRouteImport } from './routes/for-perfumes-beauty'
import { Route as ForKidsBabyRouteImport } from './routes/for-kids-baby'
import { Route as ForHomeDecorRouteImport } from './routes/for-home-decor'
import { Route as ForGiftsSweetsCoffeeRouteImport } from './routes/for-gifts-sweets-coffee'
import { Route as ForElectronicsAccessoriesRouteImport } from './routes/for-electronics-accessories'
import { Route as ForAbayasFashionRouteImport } from './routes/for-abayas-fashion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessSolutionsRouteImport } from './routes/business-solutions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as OnboardingWizardRouteImport } from './routes/onboarding.wizard'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as HooksOnboardingEmailsRouteImport } from './routes/hooks/onboarding-emails'
import { Route as HooksExpiringSubscriptionsRouteImport } from './routes/hooks/expiring-subscriptions'
import { Route as HooksDomainScanRouteImport } from './routes/hooks/domain-scan'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DashboardUsageRouteImport } from './routes/dashboard.usage'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardStoreProfileRouteImport } from './routes/dashboard.store-profile'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardLibraryRouteImport } from './routes/dashboard.library'
import { Route as DashboardGenerateVideoRouteImport } from './routes/dashboard.generate-video'
import { Route as DashboardGenerateTextRouteImport } from './routes/dashboard.generate-text'
import { Route as DashboardGenerateImageRouteImport } from './routes/dashboard.generate-image'
import { Route as DashboardEditImageRouteImport } from './routes/dashboard.edit-image'
import { Route as DashboardCreditsRouteImport } from './routes/dashboard.credits'
import { Route as DashboardCampaignStudioRouteImport } from './routes/dashboard.campaign-studio'
import { Route as ApiTelegramSetChatIdRouteImport } from './routes/api.telegram-set-chat-id'
import { Route as ApiTelegramDiscoverChatsRouteImport } from './routes/api.telegram-discover-chats'
import { Route as ApiSetupNotifyConfigRouteImport } from './routes/api.setup-notify-config'
import { Route as ApiNotifyTelegramAdminRouteImport } from './routes/api.notify-telegram-admin'
import { Route as AdminVideoProvidersRouteImport } from './routes/admin.video-providers'
import { Route as AdminVideoProviderRouteImport } from './routes/admin.video-provider'
import { Route as AdminVideoProvideRouteImport } from './routes/admin.video-provide'
import { Route as AdminVideoJobsRouteImport } from './routes/admin.video-jobs'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminReconcileRouteImport } from './routes/admin.reconcile'
import { Route as AdminPlanLimitsRouteImport } from './routes/admin.plan-limits'
import { Route as AdminPhase1MonitorRouteImport } from './routes/admin.phase1-monitor'
import { Route as AdminEmailMonitorRouteImport } from './routes/admin.email-monitor'
import { Route as AdminDomainScanRouteImport } from './routes/admin.domain-scan'
import { Route as AdminDnsCheckRouteImport } from './routes/admin.dns-check'
import { Route as AdminCreditsRouteImport } from './routes/admin.credits'
import { Route as AdminCreditLedgerRouteImport } from './routes/admin.credit-ledger'
import { Route as AdminContactSubmissionsRouteImport } from './routes/admin.contact-submissions'
import { Route as AdminCampaignPacksRouteImport } from './routes/admin.campaign-packs'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAbuseMonitorRouteImport } from './routes/admin.abuse-monitor'
import { Route as AdminAbTestsRouteImport } from './routes/admin.ab-tests'
import { Route as DashboardBillingIndexRouteImport } from './routes/dashboard.billing.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicVideoProviderCallbackRouteImport } from './routes/api.public.video-provider-callback'
import { Route as ApiPublicContactSubmitRouteImport } from './routes/api.public.contact-submit'
import { Route as ApiInvoiceRequestIdRouteImport } from './routes/api.invoice.$requestId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as DashboardBillingConfirmRequestIdRouteImport } from './routes/dashboard.billing.confirm.$requestId'
import { Route as ApiPublicHooksPhase1DailyReportRouteImport } from './routes/api.public.hooks.phase1-daily-report'
import { Route as ApiPublicHooksOcrReceiptRouteImport } from './routes/api.public.hooks.ocr-receipt'
import { Route as ApiPublicHooksCheckStaleSubscriptionsRouteImport } from './routes/api.public.hooks.check-stale-subscriptions'
import { Route as ApiPublicHooksCheckEmailDlqRouteImport } from './routes/api.public.hooks.check-email-dlq'
import { Route as ApiPublicHooksActivationSequenceRouteImport } from './routes/api.public.hooks.activation-sequence'

const VsChatgptRoute = VsChatgptRouteImport.update({
  id: '/vs-chatgpt',
  path: '/vs-chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoProvidersRoute = VideoProvidersRouteImport.update({
  id: '/video-providers',
  path: '/video-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoProviderRoute = VideoProviderRouteImport.update({
  id: '/video-provider',
  path: '/video-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofCenterRoute = ProofCenterRouteImport.update({
  id: '/proof-center',
  path: '/proof-center',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPerfumesBeautyRoute = ForPerfumesBeautyRouteImport.update({
  id: '/for-perfumes-beauty',
  path: '/for-perfumes-beauty',
  getParentRoute: () => rootRouteImport,
} as any)
const ForKidsBabyRoute = ForKidsBabyRouteImport.update({
  id: '/for-kids-baby',
  path: '/for-kids-baby',
  getParentRoute: () => rootRouteImport,
} as any)
const ForHomeDecorRoute = ForHomeDecorRouteImport.update({
  id: '/for-home-decor',
  path: '/for-home-decor',
  getParentRoute: () => rootRouteImport,
} as any)
const ForGiftsSweetsCoffeeRoute = ForGiftsSweetsCoffeeRouteImport.update({
  id: '/for-gifts-sweets-coffee',
  path: '/for-gifts-sweets-coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const ForElectronicsAccessoriesRoute =
  ForElectronicsAccessoriesRouteImport.update({
    id: '/for-electronics-accessories',
    path: '/for-electronics-accessories',
    getParentRoute: () => rootRouteImport,
  } as any)
const ForAbayasFashionRoute = ForAbayasFashionRouteImport.update({
  id: '/for-abayas-fashion',
  path: '/for-abayas-fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSolutionsRoute = BusinessSolutionsRouteImport.update({
  id: '/business-solutions',
  path: '/business-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const OnboardingWizardRoute = OnboardingWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => OnboardingRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksOnboardingEmailsRoute = HooksOnboardingEmailsRouteImport.update({
  id: '/hooks/onboarding-emails',
  path: '/hooks/onboarding-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksExpiringSubscriptionsRoute =
  HooksExpiringSubscriptionsRouteImport.update({
    id: '/hooks/expiring-subscriptions',
    path: '/hooks/expiring-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksDomainScanRoute = HooksDomainScanRouteImport.update({
  id: '/hooks/domain-scan',
  path: '/hooks/domain-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStoreProfileRoute = DashboardStoreProfileRouteImport.update({
  id: '/store-profile',
  path: '/store-profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGenerateVideoRoute = DashboardGenerateVideoRouteImport.update({
  id: '/generate-video',
  path: '/generate-video',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGenerateTextRoute = DashboardGenerateTextRouteImport.update({
  id: '/generate-text',
  path: '/generate-text',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGenerateImageRoute = DashboardGenerateImageRouteImport.update({
  id: '/generate-image',
  path: '/generate-image',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditImageRoute = DashboardEditImageRouteImport.update({
  id: '/edit-image',
  path: '/edit-image',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreditsRoute = DashboardCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignStudioRoute = DashboardCampaignStudioRouteImport.update({
  id: '/campaign-studio',
  path: '/campaign-studio',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiTelegramSetChatIdRoute = ApiTelegramSetChatIdRouteImport.update({
  id: '/api/telegram-set-chat-id',
  path: '/api/telegram-set-chat-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramDiscoverChatsRoute =
  ApiTelegramDiscoverChatsRouteImport.update({
    id: '/api/telegram-discover-chats',
    path: '/api/telegram-discover-chats',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSetupNotifyConfigRoute = ApiSetupNotifyConfigRouteImport.update({
  id: '/api/setup-notify-config',
  path: '/api/setup-notify-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyTelegramAdminRoute = ApiNotifyTelegramAdminRouteImport.update({
  id: '/api/notify-telegram-admin',
  path: '/api/notify-telegram-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideoProvidersRoute = AdminVideoProvidersRouteImport.update({
  id: '/admin/video-providers',
  path: '/admin/video-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideoProviderRoute = AdminVideoProviderRouteImport.update({
  id: '/admin/video-provider',
  path: '/admin/video-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideoProvideRoute = AdminVideoProvideRouteImport.update({
  id: '/admin/video-provide',
  path: '/admin/video-provide',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideoJobsRoute = AdminVideoJobsRouteImport.update({
  id: '/admin/video-jobs',
  path: '/admin/video-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReconcileRoute = AdminReconcileRouteImport.update({
  id: '/admin/reconcile',
  path: '/admin/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlanLimitsRoute = AdminPlanLimitsRouteImport.update({
  id: '/admin/plan-limits',
  path: '/admin/plan-limits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhase1MonitorRoute = AdminPhase1MonitorRouteImport.update({
  id: '/admin/phase1-monitor',
  path: '/admin/phase1-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailMonitorRoute = AdminEmailMonitorRouteImport.update({
  id: '/admin/email-monitor',
  path: '/admin/email-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDomainScanRoute = AdminDomainScanRouteImport.update({
  id: '/admin/domain-scan',
  path: '/admin/domain-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDnsCheckRoute = AdminDnsCheckRouteImport.update({
  id: '/admin/dns-check',
  path: '/admin/dns-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreditsRoute = AdminCreditsRouteImport.update({
  id: '/admin/credits',
  path: '/admin/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreditLedgerRoute = AdminCreditLedgerRouteImport.update({
  id: '/admin/credit-ledger',
  path: '/admin/credit-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactSubmissionsRoute = AdminContactSubmissionsRouteImport.update({
  id: '/admin/contact-submissions',
  path: '/admin/contact-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignPacksRoute = AdminCampaignPacksRouteImport.update({
  id: '/admin/campaign-packs',
  path: '/admin/campaign-packs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAbuseMonitorRoute = AdminAbuseMonitorRouteImport.update({
  id: '/admin/abuse-monitor',
  path: '/admin/abuse-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAbTestsRoute = AdminAbTestsRouteImport.update({
  id: '/admin/ab-tests',
  path: '/admin/ab-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBillingIndexRoute = DashboardBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => DashboardRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVideoProviderCallbackRoute =
  ApiPublicVideoProviderCallbackRouteImport.update({
    id: '/api/public/video-provider-callback',
    path: '/api/public/video-provider-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContactSubmitRoute = ApiPublicContactSubmitRouteImport.update({
  id: '/api/public/contact-submit',
  path: '/api/public/contact-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoiceRequestIdRoute = ApiInvoiceRequestIdRouteImport.update({
  id: '/api/invoice/$requestId',
  path: '/api/invoice/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBillingConfirmRequestIdRoute =
  DashboardBillingConfirmRequestIdRouteImport.update({
    id: '/billing/confirm/$requestId',
    path: '/billing/confirm/$requestId',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiPublicHooksPhase1DailyReportRoute =
  ApiPublicHooksPhase1DailyReportRouteImport.update({
    id: '/api/public/hooks/phase1-daily-report',
    path: '/api/public/hooks/phase1-daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOcrReceiptRoute =
  ApiPublicHooksOcrReceiptRouteImport.update({
    id: '/api/public/hooks/ocr-receipt',
    path: '/api/public/hooks/ocr-receipt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckStaleSubscriptionsRoute =
  ApiPublicHooksCheckStaleSubscriptionsRouteImport.update({
    id: '/api/public/hooks/check-stale-subscriptions',
    path: '/api/public/hooks/check-stale-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckEmailDlqRoute =
  ApiPublicHooksCheckEmailDlqRouteImport.update({
    id: '/api/public/hooks/check-email-dlq',
    path: '/api/public/hooks/check-email-dlq',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksActivationSequenceRoute =
  ApiPublicHooksActivationSequenceRouteImport.update({
    id: '/api/public/hooks/activation-sequence',
    path: '/api/public/hooks/activation-sequence',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business-solutions': typeof BusinessSolutionsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/for-abayas-fashion': typeof ForAbayasFashionRoute
  '/for-electronics-accessories': typeof ForElectronicsAccessoriesRoute
  '/for-gifts-sweets-coffee': typeof ForGiftsSweetsCoffeeRoute
  '/for-home-decor': typeof ForHomeDecorRoute
  '/for-kids-baby': typeof ForKidsBabyRoute
  '/for-perfumes-beauty': typeof ForPerfumesBeautyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/proof-center': typeof ProofCenterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/video-provider': typeof VideoProviderRoute
  '/video-providers': typeof VideoProvidersRoute
  '/vs-chatgpt': typeof VsChatgptRoute
  '/admin/ab-tests': typeof AdminAbTestsRoute
  '/admin/abuse-monitor': typeof AdminAbuseMonitorRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/campaign-packs': typeof AdminCampaignPacksRoute
  '/admin/contact-submissions': typeof AdminContactSubmissionsRoute
  '/admin/credit-ledger': typeof AdminCreditLedgerRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/dns-check': typeof AdminDnsCheckRoute
  '/admin/domain-scan': typeof AdminDomainScanRoute
  '/admin/email-monitor': typeof AdminEmailMonitorRoute
  '/admin/phase1-monitor': typeof AdminPhase1MonitorRoute
  '/admin/plan-limits': typeof AdminPlanLimitsRoute
  '/admin/reconcile': typeof AdminReconcileRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/video-jobs': typeof AdminVideoJobsRoute
  '/admin/video-provide': typeof AdminVideoProvideRoute
  '/admin/video-provider': typeof AdminVideoProviderRoute
  '/admin/video-providers': typeof AdminVideoProvidersRoute
  '/api/notify-telegram-admin': typeof ApiNotifyTelegramAdminRoute
  '/api/setup-notify-config': typeof ApiSetupNotifyConfigRoute
  '/api/telegram-discover-chats': typeof ApiTelegramDiscoverChatsRoute
  '/api/telegram-set-chat-id': typeof ApiTelegramSetChatIdRoute
  '/dashboard/campaign-studio': typeof DashboardCampaignStudioRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/edit-image': typeof DashboardEditImageRoute
  '/dashboard/generate-image': typeof DashboardGenerateImageRoute
  '/dashboard/generate-text': typeof DashboardGenerateTextRoute
  '/dashboard/generate-video': typeof DashboardGenerateVideoRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/store-profile': typeof DashboardStoreProfileRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hooks/domain-scan': typeof HooksDomainScanRoute
  '/hooks/expiring-subscriptions': typeof HooksExpiringSubscriptionsRoute
  '/hooks/onboarding-emails': typeof HooksOnboardingEmailsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/onboarding/wizard': typeof OnboardingWizardRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/invoice/$requestId': typeof ApiInvoiceRequestIdRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/api/public/video-provider-callback': typeof ApiPublicVideoProviderCallbackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/api/public/hooks/activation-sequence': typeof ApiPublicHooksActivationSequenceRoute
  '/api/public/hooks/check-email-dlq': typeof ApiPublicHooksCheckEmailDlqRoute
  '/api/public/hooks/check-stale-subscriptions': typeof ApiPublicHooksCheckStaleSubscriptionsRoute
  '/api/public/hooks/ocr-receipt': typeof ApiPublicHooksOcrReceiptRoute
  '/api/public/hooks/phase1-daily-report': typeof ApiPublicHooksPhase1DailyReportRoute
  '/dashboard/billing/confirm/$requestId': typeof DashboardBillingConfirmRequestIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business-solutions': typeof BusinessSolutionsRoute
  '/contact': typeof ContactRoute
  '/for-abayas-fashion': typeof ForAbayasFashionRoute
  '/for-electronics-accessories': typeof ForElectronicsAccessoriesRoute
  '/for-gifts-sweets-coffee': typeof ForGiftsSweetsCoffeeRoute
  '/for-home-decor': typeof ForHomeDecorRoute
  '/for-kids-baby': typeof ForKidsBabyRoute
  '/for-perfumes-beauty': typeof ForPerfumesBeautyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/proof-center': typeof ProofCenterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/video-provider': typeof VideoProviderRoute
  '/video-providers': typeof VideoProvidersRoute
  '/vs-chatgpt': typeof VsChatgptRoute
  '/admin/ab-tests': typeof AdminAbTestsRoute
  '/admin/abuse-monitor': typeof AdminAbuseMonitorRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/campaign-packs': typeof AdminCampaignPacksRoute
  '/admin/contact-submissions': typeof AdminContactSubmissionsRoute
  '/admin/credit-ledger': typeof AdminCreditLedgerRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/dns-check': typeof AdminDnsCheckRoute
  '/admin/domain-scan': typeof AdminDomainScanRoute
  '/admin/email-monitor': typeof AdminEmailMonitorRoute
  '/admin/phase1-monitor': typeof AdminPhase1MonitorRoute
  '/admin/plan-limits': typeof AdminPlanLimitsRoute
  '/admin/reconcile': typeof AdminReconcileRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/video-jobs': typeof AdminVideoJobsRoute
  '/admin/video-provide': typeof AdminVideoProvideRoute
  '/admin/video-provider': typeof AdminVideoProviderRoute
  '/admin/video-providers': typeof AdminVideoProvidersRoute
  '/api/notify-telegram-admin': typeof ApiNotifyTelegramAdminRoute
  '/api/setup-notify-config': typeof ApiSetupNotifyConfigRoute
  '/api/telegram-discover-chats': typeof ApiTelegramDiscoverChatsRoute
  '/api/telegram-set-chat-id': typeof ApiTelegramSetChatIdRoute
  '/dashboard/campaign-studio': typeof DashboardCampaignStudioRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/edit-image': typeof DashboardEditImageRoute
  '/dashboard/generate-image': typeof DashboardGenerateImageRoute
  '/dashboard/generate-text': typeof DashboardGenerateTextRoute
  '/dashboard/generate-video': typeof DashboardGenerateVideoRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/store-profile': typeof DashboardStoreProfileRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hooks/domain-scan': typeof HooksDomainScanRoute
  '/hooks/expiring-subscriptions': typeof HooksExpiringSubscriptionsRoute
  '/hooks/onboarding-emails': typeof HooksOnboardingEmailsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/onboarding/wizard': typeof OnboardingWizardRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/invoice/$requestId': typeof ApiInvoiceRequestIdRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/api/public/video-provider-callback': typeof ApiPublicVideoProviderCallbackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dashboard/billing': typeof DashboardBillingIndexRoute
  '/api/public/hooks/activation-sequence': typeof ApiPublicHooksActivationSequenceRoute
  '/api/public/hooks/check-email-dlq': typeof ApiPublicHooksCheckEmailDlqRoute
  '/api/public/hooks/check-stale-subscriptions': typeof ApiPublicHooksCheckStaleSubscriptionsRoute
  '/api/public/hooks/ocr-receipt': typeof ApiPublicHooksOcrReceiptRoute
  '/api/public/hooks/phase1-daily-report': typeof ApiPublicHooksPhase1DailyReportRoute
  '/dashboard/billing/confirm/$requestId': typeof DashboardBillingConfirmRequestIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business-solutions': typeof BusinessSolutionsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/for-abayas-fashion': typeof ForAbayasFashionRoute
  '/for-electronics-accessories': typeof ForElectronicsAccessoriesRoute
  '/for-gifts-sweets-coffee': typeof ForGiftsSweetsCoffeeRoute
  '/for-home-decor': typeof ForHomeDecorRoute
  '/for-kids-baby': typeof ForKidsBabyRoute
  '/for-perfumes-beauty': typeof ForPerfumesBeautyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/proof-center': typeof ProofCenterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/video-provider': typeof VideoProviderRoute
  '/video-providers': typeof VideoProvidersRoute
  '/vs-chatgpt': typeof VsChatgptRoute
  '/admin/ab-tests': typeof AdminAbTestsRoute
  '/admin/abuse-monitor': typeof AdminAbuseMonitorRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/campaign-packs': typeof AdminCampaignPacksRoute
  '/admin/contact-submissions': typeof AdminContactSubmissionsRoute
  '/admin/credit-ledger': typeof AdminCreditLedgerRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/dns-check': typeof AdminDnsCheckRoute
  '/admin/domain-scan': typeof AdminDomainScanRoute
  '/admin/email-monitor': typeof AdminEmailMonitorRoute
  '/admin/phase1-monitor': typeof AdminPhase1MonitorRoute
  '/admin/plan-limits': typeof AdminPlanLimitsRoute
  '/admin/reconcile': typeof AdminReconcileRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/video-jobs': typeof AdminVideoJobsRoute
  '/admin/video-provide': typeof AdminVideoProvideRoute
  '/admin/video-provider': typeof AdminVideoProviderRoute
  '/admin/video-providers': typeof AdminVideoProvidersRoute
  '/api/notify-telegram-admin': typeof ApiNotifyTelegramAdminRoute
  '/api/setup-notify-config': typeof ApiSetupNotifyConfigRoute
  '/api/telegram-discover-chats': typeof ApiTelegramDiscoverChatsRoute
  '/api/telegram-set-chat-id': typeof ApiTelegramSetChatIdRoute
  '/dashboard/campaign-studio': typeof DashboardCampaignStudioRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/edit-image': typeof DashboardEditImageRoute
  '/dashboard/generate-image': typeof DashboardGenerateImageRoute
  '/dashboard/generate-text': typeof DashboardGenerateTextRoute
  '/dashboard/generate-video': typeof DashboardGenerateVideoRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/store-profile': typeof DashboardStoreProfileRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hooks/domain-scan': typeof HooksDomainScanRoute
  '/hooks/expiring-subscriptions': typeof HooksExpiringSubscriptionsRoute
  '/hooks/onboarding-emails': typeof HooksOnboardingEmailsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/onboarding/wizard': typeof OnboardingWizardRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/invoice/$requestId': typeof ApiInvoiceRequestIdRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/api/public/video-provider-callback': typeof ApiPublicVideoProviderCallbackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/api/public/hooks/activation-sequence': typeof ApiPublicHooksActivationSequenceRoute
  '/api/public/hooks/check-email-dlq': typeof ApiPublicHooksCheckEmailDlqRoute
  '/api/public/hooks/check-stale-subscriptions': typeof ApiPublicHooksCheckStaleSubscriptionsRoute
  '/api/public/hooks/ocr-receipt': typeof ApiPublicHooksOcrReceiptRoute
  '/api/public/hooks/phase1-daily-report': typeof ApiPublicHooksPhase1DailyReportRoute
  '/dashboard/billing/confirm/$requestId': typeof DashboardBillingConfirmRequestIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/business-solutions'
    | '/contact'
    | '/dashboard'
    | '/for-abayas-fashion'
    | '/for-electronics-accessories'
    | '/for-gifts-sweets-coffee'
    | '/for-home-decor'
    | '/for-kids-baby'
    | '/for-perfumes-beauty'
    | '/forgot-password'
    | '/library'
    | '/onboarding'
    | '/pricing'
    | '/proof-center'
    | '/reset-password'
    | '/unsubscribe'
    | '/video-provider'
    | '/video-providers'
    | '/vs-chatgpt'
    | '/admin/ab-tests'
    | '/admin/abuse-monitor'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/campaign-packs'
    | '/admin/contact-submissions'
    | '/admin/credit-ledger'
    | '/admin/credits'
    | '/admin/dns-check'
    | '/admin/domain-scan'
    | '/admin/email-monitor'
    | '/admin/phase1-monitor'
    | '/admin/plan-limits'
    | '/admin/reconcile'
    | '/admin/subscriptions'
    | '/admin/video-jobs'
    | '/admin/video-provide'
    | '/admin/video-provider'
    | '/admin/video-providers'
    | '/api/notify-telegram-admin'
    | '/api/setup-notify-config'
    | '/api/telegram-discover-chats'
    | '/api/telegram-set-chat-id'
    | '/dashboard/campaign-studio'
    | '/dashboard/credits'
    | '/dashboard/edit-image'
    | '/dashboard/generate-image'
    | '/dashboard/generate-text'
    | '/dashboard/generate-video'
    | '/dashboard/library'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/store-profile'
    | '/dashboard/templates'
    | '/dashboard/usage'
    | '/email/unsubscribe'
    | '/hooks/domain-scan'
    | '/hooks/expiring-subscriptions'
    | '/hooks/onboarding-emails'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/onboarding/wizard'
    | '/dashboard/'
    | '/api/invoice/$requestId'
    | '/api/public/contact-submit'
    | '/api/public/video-provider-callback'
    | '/lovable/email/suppression'
    | '/dashboard/billing/'
    | '/api/public/hooks/activation-sequence'
    | '/api/public/hooks/check-email-dlq'
    | '/api/public/hooks/check-stale-subscriptions'
    | '/api/public/hooks/ocr-receipt'
    | '/api/public/hooks/phase1-daily-report'
    | '/dashboard/billing/confirm/$requestId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/business-solutions'
    | '/contact'
    | '/for-abayas-fashion'
    | '/for-electronics-accessories'
    | '/for-gifts-sweets-coffee'
    | '/for-home-decor'
    | '/for-kids-baby'
    | '/for-perfumes-beauty'
    | '/forgot-password'
    | '/library'
    | '/onboarding'
    | '/pricing'
    | '/proof-center'
    | '/reset-password'
    | '/unsubscribe'
    | '/video-provider'
    | '/video-providers'
    | '/vs-chatgpt'
    | '/admin/ab-tests'
    | '/admin/abuse-monitor'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/campaign-packs'
    | '/admin/contact-submissions'
    | '/admin/credit-ledger'
    | '/admin/credits'
    | '/admin/dns-check'
    | '/admin/domain-scan'
    | '/admin/email-monitor'
    | '/admin/phase1-monitor'
    | '/admin/plan-limits'
    | '/admin/reconcile'
    | '/admin/subscriptions'
    | '/admin/video-jobs'
    | '/admin/video-provide'
    | '/admin/video-provider'
    | '/admin/video-providers'
    | '/api/notify-telegram-admin'
    | '/api/setup-notify-config'
    | '/api/telegram-discover-chats'
    | '/api/telegram-set-chat-id'
    | '/dashboard/campaign-studio'
    | '/dashboard/credits'
    | '/dashboard/edit-image'
    | '/dashboard/generate-image'
    | '/dashboard/generate-text'
    | '/dashboard/generate-video'
    | '/dashboard/library'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/store-profile'
    | '/dashboard/templates'
    | '/dashboard/usage'
    | '/email/unsubscribe'
    | '/hooks/domain-scan'
    | '/hooks/expiring-subscriptions'
    | '/hooks/onboarding-emails'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/onboarding/wizard'
    | '/dashboard'
    | '/api/invoice/$requestId'
    | '/api/public/contact-submit'
    | '/api/public/video-provider-callback'
    | '/lovable/email/suppression'
    | '/dashboard/billing'
    | '/api/public/hooks/activation-sequence'
    | '/api/public/hooks/check-email-dlq'
    | '/api/public/hooks/check-stale-subscriptions'
    | '/api/public/hooks/ocr-receipt'
    | '/api/public/hooks/phase1-daily-report'
    | '/dashboard/billing/confirm/$requestId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/business-solutions'
    | '/contact'
    | '/dashboard'
    | '/for-abayas-fashion'
    | '/for-electronics-accessories'
    | '/for-gifts-sweets-coffee'
    | '/for-home-decor'
    | '/for-kids-baby'
    | '/for-perfumes-beauty'
    | '/forgot-password'
    | '/library'
    | '/onboarding'
    | '/pricing'
    | '/proof-center'
    | '/reset-password'
    | '/unsubscribe'
    | '/video-provider'
    | '/video-providers'
    | '/vs-chatgpt'
    | '/admin/ab-tests'
    | '/admin/abuse-monitor'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/campaign-packs'
    | '/admin/contact-submissions'
    | '/admin/credit-ledger'
    | '/admin/credits'
    | '/admin/dns-check'
    | '/admin/domain-scan'
    | '/admin/email-monitor'
    | '/admin/phase1-monitor'
    | '/admin/plan-limits'
    | '/admin/reconcile'
    | '/admin/subscriptions'
    | '/admin/video-jobs'
    | '/admin/video-provide'
    | '/admin/video-provider'
    | '/admin/video-providers'
    | '/api/notify-telegram-admin'
    | '/api/setup-notify-config'
    | '/api/telegram-discover-chats'
    | '/api/telegram-set-chat-id'
    | '/dashboard/campaign-studio'
    | '/dashboard/credits'
    | '/dashboard/edit-image'
    | '/dashboard/generate-image'
    | '/dashboard/generate-text'
    | '/dashboard/generate-video'
    | '/dashboard/library'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/store-profile'
    | '/dashboard/templates'
    | '/dashboard/usage'
    | '/email/unsubscribe'
    | '/hooks/domain-scan'
    | '/hooks/expiring-subscriptions'
    | '/hooks/onboarding-emails'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/onboarding/wizard'
    | '/dashboard/'
    | '/api/invoice/$requestId'
    | '/api/public/contact-submit'
    | '/api/public/video-provider-callback'
    | '/lovable/email/suppression'
    | '/dashboard/billing/'
    | '/api/public/hooks/activation-sequence'
    | '/api/public/hooks/check-email-dlq'
    | '/api/public/hooks/check-stale-subscriptions'
    | '/api/public/hooks/ocr-receipt'
    | '/api/public/hooks/phase1-daily-report'
    | '/dashboard/billing/confirm/$requestId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BusinessSolutionsRoute: typeof BusinessSolutionsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForAbayasFashionRoute: typeof ForAbayasFashionRoute
  ForElectronicsAccessoriesRoute: typeof ForElectronicsAccessoriesRoute
  ForGiftsSweetsCoffeeRoute: typeof ForGiftsSweetsCoffeeRoute
  ForHomeDecorRoute: typeof ForHomeDecorRoute
  ForKidsBabyRoute: typeof ForKidsBabyRoute
  ForPerfumesBeautyRoute: typeof ForPerfumesBeautyRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LibraryRoute: typeof LibraryRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProofCenterRoute: typeof ProofCenterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VideoProviderRoute: typeof VideoProviderRoute
  VideoProvidersRoute: typeof VideoProvidersRoute
  VsChatgptRoute: typeof VsChatgptRoute
  AdminAbTestsRoute: typeof AdminAbTestsRoute
  AdminAbuseMonitorRoute: typeof AdminAbuseMonitorRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCampaignPacksRoute: typeof AdminCampaignPacksRoute
  AdminContactSubmissionsRoute: typeof AdminContactSubmissionsRoute
  AdminCreditLedgerRoute: typeof AdminCreditLedgerRoute
  AdminCreditsRoute: typeof AdminCreditsRoute
  AdminDnsCheckRoute: typeof AdminDnsCheckRoute
  AdminDomainScanRoute: typeof AdminDomainScanRoute
  AdminEmailMonitorRoute: typeof AdminEmailMonitorRoute
  AdminPhase1MonitorRoute: typeof AdminPhase1MonitorRoute
  AdminPlanLimitsRoute: typeof AdminPlanLimitsRoute
  AdminReconcileRoute: typeof AdminReconcileRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminVideoJobsRoute: typeof AdminVideoJobsRoute
  AdminVideoProvideRoute: typeof AdminVideoProvideRoute
  AdminVideoProviderRoute: typeof AdminVideoProviderRoute
  AdminVideoProvidersRoute: typeof AdminVideoProvidersRoute
  ApiNotifyTelegramAdminRoute: typeof ApiNotifyTelegramAdminRoute
  ApiSetupNotifyConfigRoute: typeof ApiSetupNotifyConfigRoute
  ApiTelegramDiscoverChatsRoute: typeof ApiTelegramDiscoverChatsRoute
  ApiTelegramSetChatIdRoute: typeof ApiTelegramSetChatIdRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  HooksDomainScanRoute: typeof HooksDomainScanRoute
  HooksExpiringSubscriptionsRoute: typeof HooksExpiringSubscriptionsRoute
  HooksOnboardingEmailsRoute: typeof HooksOnboardingEmailsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiInvoiceRequestIdRoute: typeof ApiInvoiceRequestIdRoute
  ApiPublicContactSubmitRoute: typeof ApiPublicContactSubmitRoute
  ApiPublicVideoProviderCallbackRoute: typeof ApiPublicVideoProviderCallbackRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksActivationSequenceRoute: typeof ApiPublicHooksActivationSequenceRoute
  ApiPublicHooksCheckEmailDlqRoute: typeof ApiPublicHooksCheckEmailDlqRoute
  ApiPublicHooksCheckStaleSubscriptionsRoute: typeof ApiPublicHooksCheckStaleSubscriptionsRoute
  ApiPublicHooksOcrReceiptRoute: typeof ApiPublicHooksOcrReceiptRoute
  ApiPublicHooksPhase1DailyReportRoute: typeof ApiPublicHooksPhase1DailyReportRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vs-chatgpt': {
      id: '/vs-chatgpt'
      path: '/vs-chatgpt'
      fullPath: '/vs-chatgpt'
      preLoaderRoute: typeof VsChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-providers': {
      id: '/video-providers'
      path: '/video-providers'
      fullPath: '/video-providers'
      preLoaderRoute: typeof VideoProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-provider': {
      id: '/video-provider'
      path: '/video-provider'
      fullPath: '/video-provider'
      preLoaderRoute: typeof VideoProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof-center': {
      id: '/proof-center'
      path: '/proof-center'
      fullPath: '/proof-center'
      preLoaderRoute: typeof ProofCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-perfumes-beauty': {
      id: '/for-perfumes-beauty'
      path: '/for-perfumes-beauty'
      fullPath: '/for-perfumes-beauty'
      preLoaderRoute: typeof ForPerfumesBeautyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-kids-baby': {
      id: '/for-kids-baby'
      path: '/for-kids-baby'
      fullPath: '/for-kids-baby'
      preLoaderRoute: typeof ForKidsBabyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-home-decor': {
      id: '/for-home-decor'
      path: '/for-home-decor'
      fullPath: '/for-home-decor'
      preLoaderRoute: typeof ForHomeDecorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-gifts-sweets-coffee': {
      id: '/for-gifts-sweets-coffee'
      path: '/for-gifts-sweets-coffee'
      fullPath: '/for-gifts-sweets-coffee'
      preLoaderRoute: typeof ForGiftsSweetsCoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-electronics-accessories': {
      id: '/for-electronics-accessories'
      path: '/for-electronics-accessories'
      fullPath: '/for-electronics-accessories'
      preLoaderRoute: typeof ForElectronicsAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-abayas-fashion': {
      id: '/for-abayas-fashion'
      path: '/for-abayas-fashion'
      fullPath: '/for-abayas-fashion'
      preLoaderRoute: typeof ForAbayasFashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-solutions': {
      id: '/business-solutions'
      path: '/business-solutions'
      fullPath: '/business-solutions'
      preLoaderRoute: typeof BusinessSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/onboarding/wizard': {
      id: '/onboarding/wizard'
      path: '/wizard'
      fullPath: '/onboarding/wizard'
      preLoaderRoute: typeof OnboardingWizardRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/onboarding-emails': {
      id: '/hooks/onboarding-emails'
      path: '/hooks/onboarding-emails'
      fullPath: '/hooks/onboarding-emails'
      preLoaderRoute: typeof HooksOnboardingEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/expiring-subscriptions': {
      id: '/hooks/expiring-subscriptions'
      path: '/hooks/expiring-subscriptions'
      fullPath: '/hooks/expiring-subscriptions'
      preLoaderRoute: typeof HooksExpiringSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/domain-scan': {
      id: '/hooks/domain-scan'
      path: '/hooks/domain-scan'
      fullPath: '/hooks/domain-scan'
      preLoaderRoute: typeof HooksDomainScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/store-profile': {
      id: '/dashboard/store-profile'
      path: '/store-profile'
      fullPath: '/dashboard/store-profile'
      preLoaderRoute: typeof DashboardStoreProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/library': {
      id: '/dashboard/library'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/generate-video': {
      id: '/dashboard/generate-video'
      path: '/generate-video'
      fullPath: '/dashboard/generate-video'
      preLoaderRoute: typeof DashboardGenerateVideoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/generate-text': {
      id: '/dashboard/generate-text'
      path: '/generate-text'
      fullPath: '/dashboard/generate-text'
      preLoaderRoute: typeof DashboardGenerateTextRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/generate-image': {
      id: '/dashboard/generate-image'
      path: '/generate-image'
      fullPath: '/dashboard/generate-image'
      preLoaderRoute: typeof DashboardGenerateImageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edit-image': {
      id: '/dashboard/edit-image'
      path: '/edit-image'
      fullPath: '/dashboard/edit-image'
      preLoaderRoute: typeof DashboardEditImageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/credits': {
      id: '/dashboard/credits'
      path: '/credits'
      fullPath: '/dashboard/credits'
      preLoaderRoute: typeof DashboardCreditsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaign-studio': {
      id: '/dashboard/campaign-studio'
      path: '/campaign-studio'
      fullPath: '/dashboard/campaign-studio'
      preLoaderRoute: typeof DashboardCampaignStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/telegram-set-chat-id': {
      id: '/api/telegram-set-chat-id'
      path: '/api/telegram-set-chat-id'
      fullPath: '/api/telegram-set-chat-id'
      preLoaderRoute: typeof ApiTelegramSetChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram-discover-chats': {
      id: '/api/telegram-discover-chats'
      path: '/api/telegram-discover-chats'
      fullPath: '/api/telegram-discover-chats'
      preLoaderRoute: typeof ApiTelegramDiscoverChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-notify-config': {
      id: '/api/setup-notify-config'
      path: '/api/setup-notify-config'
      fullPath: '/api/setup-notify-config'
      preLoaderRoute: typeof ApiSetupNotifyConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-telegram-admin': {
      id: '/api/notify-telegram-admin'
      path: '/api/notify-telegram-admin'
      fullPath: '/api/notify-telegram-admin'
      preLoaderRoute: typeof ApiNotifyTelegramAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/video-providers': {
      id: '/admin/video-providers'
      path: '/admin/video-providers'
      fullPath: '/admin/video-providers'
      preLoaderRoute: typeof AdminVideoProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/video-provider': {
      id: '/admin/video-provider'
      path: '/admin/video-provider'
      fullPath: '/admin/video-provider'
      preLoaderRoute: typeof AdminVideoProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/video-provide': {
      id: '/admin/video-provide'
      path: '/admin/video-provide'
      fullPath: '/admin/video-provide'
      preLoaderRoute: typeof AdminVideoProvideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/video-jobs': {
      id: '/admin/video-jobs'
      path: '/admin/video-jobs'
      fullPath: '/admin/video-jobs'
      preLoaderRoute: typeof AdminVideoJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reconcile': {
      id: '/admin/reconcile'
      path: '/admin/reconcile'
      fullPath: '/admin/reconcile'
      preLoaderRoute: typeof AdminReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plan-limits': {
      id: '/admin/plan-limits'
      path: '/admin/plan-limits'
      fullPath: '/admin/plan-limits'
      preLoaderRoute: typeof AdminPlanLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/phase1-monitor': {
      id: '/admin/phase1-monitor'
      path: '/admin/phase1-monitor'
      fullPath: '/admin/phase1-monitor'
      preLoaderRoute: typeof AdminPhase1MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/email-monitor': {
      id: '/admin/email-monitor'
      path: '/admin/email-monitor'
      fullPath: '/admin/email-monitor'
      preLoaderRoute: typeof AdminEmailMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/domain-scan': {
      id: '/admin/domain-scan'
      path: '/admin/domain-scan'
      fullPath: '/admin/domain-scan'
      preLoaderRoute: typeof AdminDomainScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dns-check': {
      id: '/admin/dns-check'
      path: '/admin/dns-check'
      fullPath: '/admin/dns-check'
      preLoaderRoute: typeof AdminDnsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credits': {
      id: '/admin/credits'
      path: '/admin/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AdminCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credit-ledger': {
      id: '/admin/credit-ledger'
      path: '/admin/credit-ledger'
      fullPath: '/admin/credit-ledger'
      preLoaderRoute: typeof AdminCreditLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contact-submissions': {
      id: '/admin/contact-submissions'
      path: '/admin/contact-submissions'
      fullPath: '/admin/contact-submissions'
      preLoaderRoute: typeof AdminContactSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaign-packs': {
      id: '/admin/campaign-packs'
      path: '/admin/campaign-packs'
      fullPath: '/admin/campaign-packs'
      preLoaderRoute: typeof AdminCampaignPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/abuse-monitor': {
      id: '/admin/abuse-monitor'
      path: '/admin/abuse-monitor'
      fullPath: '/admin/abuse-monitor'
      preLoaderRoute: typeof AdminAbuseMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ab-tests': {
      id: '/admin/ab-tests'
      path: '/admin/ab-tests'
      fullPath: '/admin/ab-tests'
      preLoaderRoute: typeof AdminAbTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/billing/': {
      id: '/dashboard/billing/'
      path: '/billing'
      fullPath: '/dashboard/billing/'
      preLoaderRoute: typeof DashboardBillingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/video-provider-callback': {
      id: '/api/public/video-provider-callback'
      path: '/api/public/video-provider-callback'
      fullPath: '/api/public/video-provider-callback'
      preLoaderRoute: typeof ApiPublicVideoProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact-submit': {
      id: '/api/public/contact-submit'
      path: '/api/public/contact-submit'
      fullPath: '/api/public/contact-submit'
      preLoaderRoute: typeof ApiPublicContactSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoice/$requestId': {
      id: '/api/invoice/$requestId'
      path: '/api/invoice/$requestId'
      fullPath: '/api/invoice/$requestId'
      preLoaderRoute: typeof ApiInvoiceRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/billing/confirm/$requestId': {
      id: '/dashboard/billing/confirm/$requestId'
      path: '/billing/confirm/$requestId'
      fullPath: '/dashboard/billing/confirm/$requestId'
      preLoaderRoute: typeof DashboardBillingConfirmRequestIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/hooks/phase1-daily-report': {
      id: '/api/public/hooks/phase1-daily-report'
      path: '/api/public/hooks/phase1-daily-report'
      fullPath: '/api/public/hooks/phase1-daily-report'
      preLoaderRoute: typeof ApiPublicHooksPhase1DailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ocr-receipt': {
      id: '/api/public/hooks/ocr-receipt'
      path: '/api/public/hooks/ocr-receipt'
      fullPath: '/api/public/hooks/ocr-receipt'
      preLoaderRoute: typeof ApiPublicHooksOcrReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-stale-subscriptions': {
      id: '/api/public/hooks/check-stale-subscriptions'
      path: '/api/public/hooks/check-stale-subscriptions'
      fullPath: '/api/public/hooks/check-stale-subscriptions'
      preLoaderRoute: typeof ApiPublicHooksCheckStaleSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-email-dlq': {
      id: '/api/public/hooks/check-email-dlq'
      path: '/api/public/hooks/check-email-dlq'
      fullPath: '/api/public/hooks/check-email-dlq'
      preLoaderRoute: typeof ApiPublicHooksCheckEmailDlqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/activation-sequence': {
      id: '/api/public/hooks/activation-sequence'
      path: '/api/public/hooks/activation-sequence'
      fullPath: '/api/public/hooks/activation-sequence'
      preLoaderRoute: typeof ApiPublicHooksActivationSequenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardCampaignStudioRoute: typeof DashboardCampaignStudioRoute
  DashboardCreditsRoute: typeof DashboardCreditsRoute
  DashboardEditImageRoute: typeof DashboardEditImageRoute
  DashboardGenerateImageRoute: typeof DashboardGenerateImageRoute
  DashboardGenerateTextRoute: typeof DashboardGenerateTextRoute
  DashboardGenerateVideoRoute: typeof DashboardGenerateVideoRoute
  DashboardLibraryRoute: typeof DashboardLibraryRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStoreProfileRoute: typeof DashboardStoreProfileRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBillingIndexRoute: typeof DashboardBillingIndexRoute
  DashboardBillingConfirmRequestIdRoute: typeof DashboardBillingConfirmRequestIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCampaignStudioRoute: DashboardCampaignStudioRoute,
  DashboardCreditsRoute: DashboardCreditsRoute,
  DashboardEditImageRoute: DashboardEditImageRoute,
  DashboardGenerateImageRoute: DashboardGenerateImageRoute,
  DashboardGenerateTextRoute: DashboardGenerateTextRoute,
  DashboardGenerateVideoRoute: DashboardGenerateVideoRoute,
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStoreProfileRoute: DashboardStoreProfileRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBillingIndexRoute: DashboardBillingIndexRoute,
  DashboardBillingConfirmRequestIdRoute: DashboardBillingConfirmRequestIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingWizardRoute: typeof OnboardingWizardRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingWizardRoute: OnboardingWizardRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BusinessSolutionsRoute: BusinessSolutionsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForAbayasFashionRoute: ForAbayasFashionRoute,
  ForElectronicsAccessoriesRoute: ForElectronicsAccessoriesRoute,
  ForGiftsSweetsCoffeeRoute: ForGiftsSweetsCoffeeRoute,
  ForHomeDecorRoute: ForHomeDecorRoute,
  ForKidsBabyRoute: ForKidsBabyRoute,
  ForPerfumesBeautyRoute: ForPerfumesBeautyRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LibraryRoute: LibraryRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PricingRoute: PricingRoute,
  ProofCenterRoute: ProofCenterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VideoProviderRoute: VideoProviderRoute,
  VideoProvidersRoute: VideoProvidersRoute,
  VsChatgptRoute: VsChatgptRoute,
  AdminAbTestsRoute: AdminAbTestsRoute,
  AdminAbuseMonitorRoute: AdminAbuseMonitorRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCampaignPacksRoute: AdminCampaignPacksRoute,
  AdminContactSubmissionsRoute: AdminContactSubmissionsRoute,
  AdminCreditLedgerRoute: AdminCreditLedgerRoute,
  AdminCreditsRoute: AdminCreditsRoute,
  AdminDnsCheckRoute: AdminDnsCheckRoute,
  AdminDomainScanRoute: AdminDomainScanRoute,
  AdminEmailMonitorRoute: AdminEmailMonitorRoute,
  AdminPhase1MonitorRoute: AdminPhase1MonitorRoute,
  AdminPlanLimitsRoute: AdminPlanLimitsRoute,
  AdminReconcileRoute: AdminReconcileRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminVideoJobsRoute: AdminVideoJobsRoute,
  AdminVideoProvideRoute: AdminVideoProvideRoute,
  AdminVideoProviderRoute: AdminVideoProviderRoute,
  AdminVideoProvidersRoute: AdminVideoProvidersRoute,
  ApiNotifyTelegramAdminRoute: ApiNotifyTelegramAdminRoute,
  ApiSetupNotifyConfigRoute: ApiSetupNotifyConfigRoute,
  ApiTelegramDiscoverChatsRoute: ApiTelegramDiscoverChatsRoute,
  ApiTelegramSetChatIdRoute: ApiTelegramSetChatIdRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  HooksDomainScanRoute: HooksDomainScanRoute,
  HooksExpiringSubscriptionsRoute: HooksExpiringSubscriptionsRoute,
  HooksOnboardingEmailsRoute: HooksOnboardingEmailsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiInvoiceRequestIdRoute: ApiInvoiceRequestIdRoute,
  ApiPublicContactSubmitRoute: ApiPublicContactSubmitRoute,
  ApiPublicVideoProviderCallbackRoute: ApiPublicVideoProviderCallbackRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksActivationSequenceRoute: ApiPublicHooksActivationSequenceRoute,
  ApiPublicHooksCheckEmailDlqRoute: ApiPublicHooksCheckEmailDlqRoute,
  ApiPublicHooksCheckStaleSubscriptionsRoute:
    ApiPublicHooksCheckStaleSubscriptionsRoute,
  ApiPublicHooksOcrReceiptRoute: ApiPublicHooksOcrReceiptRoute,
  ApiPublicHooksPhase1DailyReportRoute: ApiPublicHooksPhase1DailyReportRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
